In [ ]:
def alignment():
    print('aligment start')
    position = np.zeros(64)
    position[20] = position[21] = 1
    # Создаем массив значений
    value = np.zeros(64)
    values = [measure(i + 1) for i in range(len(position)) if position[i] == 1]
    value[position == 1] = values
    print(value[20])

    # Находим максимальное значение и индекс элемента с максимальным значением
    max_value = np.max(values)

    # Первоначально все элементы не меняем
    array = np.zeros(64)

    # Пока все значения не сравняются с точностью +-0.015 для самого большого изначального числа
    while np.any(np.abs(value[position == 1] - max_value) > 0.05):
        # Устанавливаем 1 на месте элементов, которые необходимо изменить
        array[position == 1] = np.where(np.abs(value[position == 1] - max_value) > 0.05, 1, array[position == 1])
        array = array.reshape((8,8))
        array = np.flip(array,axis=1)
        array = array.reshape((64,))

        print(array)

        # Запускаем функцию изменения параметров элементов
        dynamic_digital.led_matrix(hdwf, 6, 7, 5, list(array))

        # Ждем некоторое время, чтобы изменения успели примениться
        time.sleep(0.01)
        dynamic_digital.led_matrix(hdwf, 6, 7, 5, led_off)

        # Считываем новые значения и обновляем массив значений
        values = [measure(i + 1) for i in range(len(position)) if position[i] == 1]
        value[position == 1] = values

    return value

In [ ]:
import numpy as np

In [ ]:
position = np.zeros(64)
position[20] = position[21] = 1


value = np.zeros(64)
values = [1.6 for i in range(len(position)) if position[i] == 1]
value[position == 1] = values

In [ ]:
print(value)
max_value = np.max(values)
max_index = np.argmax(values)
print(np.argmax(value))


In [ ]:
array = np.zeros(64)
value[21]= 0.8

In [ ]:
np.abs(value[position == 1])

In [ ]:
array = np.zeros(64)
array[position == 1] = np.where(np.abs(value[position == 1] - max_value) > 0.1666, 1, array[position == 1])
array = array.reshape((8,8))
array = np.flip(array,axis=1)
array = array.reshape((64,))
print(array)

In [ ]:
values = [1.3 for i in range(len(position)) if position[i] == 1]
value[position == 1] = values

In [ ]:
print(value)

In [ ]:
array = np.zeros(64)
array[position == 1] = np.where(np.abs(value[position == 1] - max_value) > 0.1666, 1, array[position == 1])
array = array.reshape((8,8))
array = np.flip(array,axis=1)
array = array.reshape((64,))
print(array)

In [ ]:
import time

# Функция measure, которая возвращает значение и текущее время
def measure():
    return 42  # Пример значения, замените на реальный вызов функции

weights_array = []

start_time = time.time()
while len(weights_array)<10:
    value = measure()
    current_time = time.time() - start_time  
    # current_time = time.strftime("%S", time.localtime())
    time.sleep(1)
    weights_array.append((value, current_time))
    time.sleep(1)
    

In [ ]:
import numpy as np

In [ ]:
weights_array

In [ ]:
np.array(weights_array)

In [ ]:
import numpy as np

pic = np.loadtxt('experiment/start.txt')
pic = pic*2.2987315479909154/255

In [ ]:
pic = pic.reshape(-1)

In [ ]:
indexes = list(range(19, 25)) + list(range(27, 33)) + [34] + list(range(36, 41)) + list(range(43, 49)) + list(range(49, 50))


In [ ]:
weights = [0] * 64

In [ ]:
for i, index in enumerate(indexes):
    weights[index-1] = pic[i]

In [ ]:
weights[27-1]

In [5]:
import pandas as pd
import numpy as np

In [6]:
pic = np.loadtxt('experiment/start.txt')
pic = pic*2.2987315479909154/255
pic.shape

(5, 5)

In [7]:
df= pd.read_csv('experiment/event.csv')
df.drop(columns=['Unnamed: 0'])

0_0  0_1  0_2  0_3  0_4  1_0  1_1  1_2  1_3  1_4  ...  3_0  3_1  3_2  \
0    0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  ...  0.0  0.0  0.0   
1    0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  ...  0.0  0.0  0.0   
2    0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  ...  0.0  0.0  0.0   
3    0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  ...  0.0  0.0  0.0   
4    0.0  0.0  0.0  0.0  0.0  0.0  0.0  1.0  0.0  0.0  ...  0.0  0.0  0.0   
..   ...  ...  ...  ...  ...  ...  ...  ...  ...  ...  ...  ...  ...  ...   
995  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  ...  0.0  0.0  0.0   
996  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  ...  0.0  0.0  0.0   
997  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  ...  0.0  0.0  0.0   
998  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  ...  0.0  0.0  0.0   
999  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  ...  0.0  0.0  0.0   

     3_3  3_4  4_0  4_1  4_2  4_3  4_4  
0    0.0  0.0  0.0  0.0  0.0  0.0  0.0  
1    0.0  0.0  0.0  0.0  0.0  0.0  0.0  
2    0.0  0.0  0.0  0.0  0.0  0.0  0.0  
3    0.0  0.0  0.0  0.0  0.0  0.0  0.0  
4    0.0  0.0  0.0  0.0  0.0  0.0  0.0  
..   ...  ...  ...  ...  ...  ...  ...  
995  0.0  0.0  0.0  0.0  0.0  0.0  0.0  
996  0.0  0.0  0.0  0.0  0.0  0.0  0.0  
997  0.0  0.0  0.0  0.0  0.0  0.0  0.0  
998  0.0  0.0  0.0  0.0  0.0  0.0  0.0  
999  0.0  0.0  0.0  0.0  0.0  0.0  0.0  

[1000 rows x 25 columns]

In [48]:
df.loc[1].to_numpy()

array([1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [ ]:
for i in range(df.shape[0]):
    print(df.loc[0])

In [ ]:
indexes = list(range(19, 25)) + list(range(27, 33)) + [34] + list(range(36, 41)) + list(range(43, 49)) + list(range(49, 51))

In [ ]:
len(indexes)

In [8]:
pic = np.loadtxt('experiment/start.txt')

pic = pic*2.2980424272707376/255
pic = pic.reshape(-1)
pic.shape

(25,)

In [9]:
leds_array = [0]*64
for i in range(1):
    for j, index in enumerate(indexes):
        leds_array = [0]*64
        leds_array[index-1] = df.loc[1].to_numpy()[j]
        leds_array= np.array(leds_array)
        print(type(leds_array))

<class 'numpy.ndarray'>
<class 'numpy.ndarray'>
<class 'numpy.ndarray'>
<class 'numpy.ndarray'>
<class 'numpy.ndarray'>
<class 'numpy.ndarray'>
<class 'numpy.ndarray'>
<class 'numpy.ndarray'>
<class 'numpy.ndarray'>
<class 'numpy.ndarray'>
<class 'numpy.ndarray'>
<class 'numpy.ndarray'>
<class 'numpy.ndarray'>
<class 'numpy.ndarray'>
<class 'numpy.ndarray'>
<class 'numpy.ndarray'>
<class 'numpy.ndarray'>
<class 'numpy.ndarray'>
<class 'numpy.ndarray'>
<class 'numpy.ndarray'>
<class 'numpy.ndarray'>
<class 'numpy.ndarray'>
<class 'numpy.ndarray'>
<class 'numpy.ndarray'>
<class 'numpy.ndarray'>


In [10]:
df.loc[1].to_numpy()[0]

1.0

In [11]:
leds_array[18]

0.0

In [1]:
w = [0]*64

In [ ]:
w[64-19]

In [ ]:
0 0 0 0 0 0 0 0 0 0     0 0 0 0 0 0 0 0 0 0    0 0 0 0 0 0 0 0 0 0    0 0 0 0 0 0 0 0 0 0   0 0 0 0 0 1 0 0 0 0    0 0 0 0 0 0 0 0 0 0 0 0 0 0





In [12]:
pic = np.loadtxt('experiment/start.txt')

pic = pic*2.2980424272707376/255
pic = pic.reshape(-1)

indexes = list(range(19, 25)) + list(range(27, 33)) + [34] + list(range(36, 41)) + list(range(43, 49)) + list(range(49, 50))
weights = [0] * 64

for i, index in enumerate(indexes):
    weights[index-1] = pic[i]

In [41]:
weights[42]

0.827404043810525

In [2]:
import time

In [37]:
df.loc[1].to_numpy()

array([1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [50]:
indexes = list(range(19, 25)) + list(range(27, 33)) + [34] + list(range(36, 41)) + list(range(43, 49)) + list(range(49, 50))
known_indices = indexes
weights_array = []



for i in range(df.shape[0]):
    leds_array = [0]*64
    for j, index in enumerate(indexes):
        leds_array[index-1] = df.loc[1].to_numpy()[j]
        leds_array= np.array(leds_array)


In [51]:
np.where(leds_array==1)

(array([18]),)

Проверка кода

In [62]:
import numpy as np

# задаем картинку
pic = np.loadtxt('experiment/start.txt')

pic = pic*2.2980424272707376/255
pic = pic.reshape(-1)

indexes = list(range(19, 25)) + list(range(27, 33)) + [34] + list(range(36, 41)) + list(range(43, 49)) + list(range(49, 50))
weights = [0] * 64

for i, index in enumerate(indexes):
    weights[index-1] = pic[i]

value = [0]*64
for i, val in enumerate(weights):
    if val != 0:
        if i<32:
            value[i]= val
        else:
            value[i] = val

In [63]:
value[37:49]

[1.2245784333781917,
 0.9580453777795657,
 2.0588293454061803,
 0,
 0,
 0.827404043810525,
 0.7912114419992837,
 1.0478812145284213,
 1.05606335201556,
 0.6898358322602487,
 1.1734284677493394,
 0.41826673012888566]

In [52]:
f = np.array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,0,0, 0, 0, 0, 0, 0, 1])
np.where(f==1)

(array([34]),)

In [3]:
import numpy as np

In [38]:
indexes = list(range(19, 25)) + list(range(27, 33)) + [34] + list(range(36, 41)) + list(range(43, 49)) + list(range(49, 50))
indexes = np.array(indexes)
np.where(indexes==32)
indexes[11]

32

In [45]:
pic = np.loadtxt('experiment/start.txt')
pic = pic.reshape(-1)
pic = pic*2.2980424272707376/255
pic

array([1.11258916, 0.96724896, 1.17337791, 0.99066264, 1.08956764,
       0.75069385, 1.04976138, 2.14462868, 1.25545015, 1.11491303,
       0.78462564, 2.0901853 , 1.02278733, 1.98073574, 1.06529508,
       1.22457843, 0.95804538, 2.05882935, 0.82740404, 0.79121144,
       1.04788121, 1.05606335, 0.68983583, 1.17342847, 0.41826673])

In [21]:
weights = [0]*64
for i, index in enumerate(indexes):
    weights[index-1] = pic[i]

weights

[0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 123.45735303027038,
 107.32982191513808,
 130.2027168771173,
 109.92789770669475,
 120.90279335571637,
 83.2999993216778,
 0,
 0,
 116.48573087776735,
 237.97659547301552,
 139.3097809325108,
 123.71521946418858,
 87.06520613132301,
 231.93533948631335,
 0,
 113.49258171529998,
 0,
 219.79037790980533,
 118.20941244747974,
 135.88413199242032,
 106.30855567968482,
 228.45595749165184,
 0,
 0,
 91.81206955446123,
 87.79599337051216,
 116.27710025445357,
 117.1850230301433,
 76.54694932472597,
 130.20832675898603,
 46.41255310048295,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0]

In [23]:
value = []
for i, val in enumerate(indexes):
    value.append(i)

In [24]:
value

[0,
 1,
 2,
 3,
 4,
 5,
 6,
 7,
 8,
 9,
 10,
 11,
 12,
 13,
 14,
 15,
 16,
 17,
 18,
 19,
 20,
 21,
 22,
 23,
 24]

In [47]:
import pandas as pd

In [65]:
df= pd.read_csv('experiment/event.csv') # файл с events
df.drop(columns=['Unnamed: 0'])
df['1_2'].sum()/df['1_2'].shape

array([0.073])

In [90]:
df['2_4'].sum()

1.0

In [11]:
import numpy as np

In [2]:
known_indices = list(range(19, 25)) + list(range(27, 33)) + [34] + list(range(36, 41)) + list(range(43, 49)) + list(range(49, 50))
len(known_indices)

25

In [79]:
weights_array=np.empty(shape=(10000,len(known_indices)))

weights_array[1][1]=1
weights_array

array([[0., 0., 0., ..., 0., 0., 0.],
       [0., 1., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       ...,
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.]])

In [71]:
for i in range(60):
    dynamic_digital.led_matrix(hdwf, 6, 7, 5, led_on)
    time.sleep(1)
    dynamic_digital.led_matrix(hdwf, 6, 7, 5, led_off)
    for j,val in enumerate(known_indices):
        if val<33:
            weights_array[i][j] = measure(val)
        else:
            weights_array[i][j] = measure_2(val)

for i in arrange(60,weights_array.shape[0]):
    time.sleep(1)
    for j,val in enumerate(known_indices):
        if val<33:
            weights_array[i][j] = measure(val)
        else:
            weights_array[i][j] = measure_2(val)


In [33]:
known_indices = list(range(19, 25)) + list(range(27, 33)) + [34] + list(range(36, 41)) + list(range(43, 49)) + list(range(49, 50))

In [45]:
known_indices

[19,
 20,
 21,
 22,
 23,
 24,
 27,
 28,
 29,
 30,
 31,
 32,
 34,
 36,
 37,
 38,
 39,
 40,
 43,
 44,
 45,
 46,
 47,
 48,
 49]

In [70]:
for _,val in enumerate(known_indices[3:6]):
    print(f"{j},{val}")
    led[val-1] = 1

2,22
2,23
2,24


In [67]:

led = [0] * 64

In [64]:
led[known_indices[0]-1:known_indices[3]-1] = [1,1,1]

In [21]:
led[18]

1

In [58]:
led = [0] * 64

led[21:24] = [1,1,1]

In [53]:
known_indices[6]-1

26

SyntaxError: invalid syntax (1881389186.py, line 1)

In [38]:
led[known_indices[3] - 1:known_indices[6] - 1]

[0, 0, 0, 0, 0]

In [69]:
len(led)

64