In [1]:
def alignment():
    print('aligment start')
    position = np.zeros(64)
    position[20] = position[21] = 1
    # Создаем массив значений
    value = np.zeros(64)
    values = [measure(i + 1) for i in range(len(position)) if position[i] == 1]
    value[position == 1] = values
    print(value[20])

    # Находим максимальное значение и индекс элемента с максимальным значением
    max_value = np.max(values)

    # Первоначально все элементы не меняем
    array = np.zeros(64)

    # Пока все значения не сравняются с точностью +-0.015 для самого большого изначального числа
    while np.any(np.abs(value[position == 1] - max_value) > 0.05):
        # Устанавливаем 1 на месте элементов, которые необходимо изменить
        array[position == 1] = np.where(np.abs(value[position == 1] - max_value) > 0.05, 1, array[position == 1])
        array = array.reshape((8,8))
        array = np.flip(array,axis=1)
        array = array.reshape((64,))

        print(array)

        # Запускаем функцию изменения параметров элементов
        dynamic_digital.led_matrix(hdwf, 6, 7, 5, list(array))

        # Ждем некоторое время, чтобы изменения успели примениться
        time.sleep(0.01)
        dynamic_digital.led_matrix(hdwf, 6, 7, 5, led_off)

        # Считываем новые значения и обновляем массив значений
        values = [measure(i + 1) for i in range(len(position)) if position[i] == 1]
        value[position == 1] = values

    return value

In [169]:
import numpy as np

In [226]:
position = np.zeros(64)
position[20] = position[21] = 1


value = np.zeros(64)
values = [1.6 for i in range(len(position)) if position[i] == 1]
value[position == 1] = values

In [244]:
print(value)
max_value = np.max(values)
max_index = np.argmax(values)
print(np.argmax(value))


[0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.
 0.  0.  1.3 1.3 0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.
 0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.
 0.  0.  0.  0.  0.  0.  0.  0.  0.  0. ]
20


In [250]:
array = np.zeros(64)
value[21]= 0.8

In [251]:
np.abs(value[position == 1])

array([1.3, 0.8])

In [256]:
array = np.zeros(64)
array[position == 1] = np.where(np.abs(value[position == 1] - max_value) > 0.1666, 1, array[position == 1])
array = array.reshape((8,8))
array = np.flip(array,axis=1)
array = array.reshape((64,))
print(array)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 1. 0. 0. 0. 0. 0.
 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


In [260]:
values = [1.3 for i in range(len(position)) if position[i] == 1]
value[position == 1] = values

In [261]:
print(value)

[0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.
 0.  0.  1.3 1.3 0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.
 0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.
 0.  0.  0.  0.  0.  0.  0.  0.  0.  0. ]


In [262]:
array = np.zeros(64)
array[position == 1] = np.where(np.abs(value[position == 1] - max_value) > 0.1666, 1, array[position == 1])
array = array.reshape((8,8))
array = np.flip(array,axis=1)
array = array.reshape((64,))
print(array)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


In [12]:
import time

# Функция measure, которая возвращает значение и текущее время
def measure():
    return 42  # Пример значения, замените на реальный вызов функции

weights_array = []

start_time = time.time()
while len(weights_array)<10:
    value = measure()
    current_time = time.time() - start_time  
    # current_time = time.strftime("%S", time.localtime())
    time.sleep(1)
    weights_array.append((value, current_time))
    time.sleep(1)
    

In [15]:
import numpy as np

In [16]:
weights_array

[(42, 0.00017595291137695312),
 (42, 2.0004630088806152),
 (42, 4.00451397895813),
 (42, 6.007872819900513),
 (42, 8.010517835617065),
 (42, 10.010979890823364),
 (42, 12.015784978866577),
 (42, 14.020681142807007),
 (42, 16.02558994293213),
 (42, 18.03240990638733)]

In [17]:
np.array(weights_array)

array([[4.20000000e+01, 1.75952911e-04],
       [4.20000000e+01, 2.00046301e+00],
       [4.20000000e+01, 4.00451398e+00],
       [4.20000000e+01, 6.00787282e+00],
       [4.20000000e+01, 8.01051784e+00],
       [4.20000000e+01, 1.00109799e+01],
       [4.20000000e+01, 1.20157850e+01],
       [4.20000000e+01, 1.40206811e+01],
       [4.20000000e+01, 1.60255899e+01],
       [4.20000000e+01, 1.80324099e+01]])

In [113]:
import numpy as np

pic = np.loadtxt('experiment/start.txt')
pic = pic*2.2987315479909154/255

array([1.11292279, 0.96753901, 1.17372978, 0.99095971, 1.08989437,
       0.75091897, 1.05007617, 2.14527179, 1.25582662, 1.11524736,
       0.78486093, 2.09081209, 1.02309403, 1.98132971, 1.06561453,
       1.22494565, 0.95833267, 2.05944673, 0.82765216, 0.7914487 ,
       1.04819545, 1.05638004, 0.6900427 , 1.17378035, 0.41839216])

In [114]:
pic = pic.reshape(-1)

In [115]:
indexes = list(range(19, 25)) + list(range(27, 33)) + [34] + list(range(36, 41)) + list(range(43, 49)) + list(range(49, 50))


In [116]:
weights = [0] * 64

In [117]:
for i, index in enumerate(indexes):
    weights[index-1] = pic[i]

In [134]:
weights[27-1]

1.0500761743509934